Repository potenday-project/Habiters_BE, pull requests merged in 2023-06, with the labels that each got.

#59 [#56] Feat : 유효성 검증 추가
  src/main/java/com/clover/habbittracker/domain/diary/api/DiaryController.java
  src/main/java/com/clover/habbittracker/domain/diary/dto/DiaryRequest.java
  src/main/java/com/clover/habbittracker/domain/habit/api/HabitController.java
  src/main/java/com/clover/habbittracker/domain/habit/dto/HabitRequest.java
  src/main/java/com/clover/habbittracker/domain/member/api/MemberController.java
  src/main/java/com/clover/habbittracker/domain/member/dto/MemberRequest.java
  src/main/java/com/clover/habbittracker/domain/member/entity/ProfileImg.java
  src/main/java/com/clover/habbittracker/domain/member/exception/MemberDuplicateNickName.java
  src/main/java/com/clover/habbittracker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/clover/habbittracker/global/dto/ErrorResponse.java
  src/main/java/com/clover/habbittracker/global/exception/ErrorType.java
  src/main/java/com/clover/habbittracker/global/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/habbittracker/global/util/DateUtil.java
  src/test/java/com/clover/habbittracker/domain/diary/api/DiaryControllerTest.java
  src/test/java/com/clover/habbittracker/domain/diary/dto/DiaryRequestTest.java
  src/test/java/com/clover/habbittracker/domain/diary/service/DiaryServiceTest.java
  src/test/java/com/clover/habbittracker/domain/habit/api/HabitControllerTest.java
  src/test/java/com/clover/habbittracker/domain/habit/dto/HabitRequestTest.java
  src/test/java/com/clover/habbittracker/domain/habit/service/HabitServiceTest.java
  src/test/java/com/clover/habbittracker/domain/member/api/MemberControllerTest.java
  src/test/java/com/clover/habbittracker/domain/member/dto/MemberRequestTest.java
  src/test/java/com/clover/habbittracker/domain/member/dto/ProfileImgTest.java
  src/test/java/com/clover/habbittracker/domain/member/service/MemberServiceTest.java
Labels: ✨feat, 🐛fix

#61 [#60] Fix : 회원 프로필 사진 및 소셜 닉네임 검증 추가
  src/main/java/com/clover/habbittracker/domain/member/entity/ProfileImg.java
  src/main/java/com/clover/habbittracker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/GoogleUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/KakaoUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/NaverUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/SocialUser.java
  src/test/java/com/clover/habbittracker/domain/member/service/MemberServiceTest.java
Labels: ✨feat, 🔨refactor, 📝docs

#62 [#56]Fix : 회고록 반환 데이터 추가
  src/main/java/com/clover/habbittracker/domain/diary/dto/DiaryResponse.java
  src/test/java/com/clover/habbittracker/domain/diary/api/DiaryControllerTest.java
Labels: 🔨refactor, 📝docs

#64 [#63] Habitimunity 엔티티 및 패키지 기본 구성
  src/main/java/com/clover/habbittracker/domain/bookmark/api/BookMarkController.java
  src/main/java/com/clover/habbittracker/domain/bookmark/entity/BookMark.java
  src/main/java/com/clover/habbittracker/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/com/clover/habbittracker/domain/bookmark/service/BookMarkService.java
  src/main/java/com/clover/habbittracker/domain/comment/api/CommentController.java
  src/main/java/com/clover/habbittracker/domain/comment/entity/Comment.java
  src/main/java/com/clover/habbittracker/domain/comment/repository/CommentRepository.java
  src/main/java/com/clover/habbittracker/domain/comment/service/CommentService.java
  src/main/java/com/clover/habbittracker/domain/like/api/LikeController.java
  src/main/java/com/clover/habbittracker/domain/like/entity/Like.java
  src/main/java/com/clover/habbittracker/domain/like/entity/Type.java
  src/main/java/com/clover/habbittracker/domain/like/repository/LikeRepository.java
  src/main/java/com/clover/habbittracker/domain/like/service/LikeService.java
  src/main/java/com/clover/habbittracker/domain/post/api/PostController.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Category.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Post.java
  src/main/java/com/clover/habbittracker/domain/post/repository/PostRepository.java
  src/main/java/com/clover/habbittracker/domain/post/service/PostService.java
  src/main/resources/schema.sql
Labels: ✨feat

#65 [#63] QueryDSL 의존성 및 예시 추가
  build.gradle
  src/main/java/com/clover/habbittracker/domain/member/repository/MemberRepository.java
  src/main/java/com/clover/habbittracker/domain/member/repository/MemberRepositoryImpl.java
Labels: ✨feat
